function space2_pow_clusterStat_cluster(loadDir,loadFile,cfg_ft,cfg_ana)

%% load the data

load(fullfile(loadDir,loadFile));

[dirs] = mm_checkDirs(dirs);

%% decide who to kick out based on trial counts

% Subjects with bad behavior
exper.badBehSub = {{'SPACE2002', 'SPACE2007', 'SPACE2025', 'SPACE2016', 'SPACE2034'}};

% SPACE2034 would also be excluded with threshold

% performance more than 2 STD below mean in some cases (e.g., lag 32):
% SPACE2007 (also rejected below)
% SPACE2025 (also rejected below)

% low trials:
% SPACE2002 (also rejected below)
% SPACE2007 (also rejected above)
% SPACE2025 (also rejected above)
% SPACE2034

evToCheck = { ...
  { ...
  { ...
  %'img_rc_onePres' ...
  %'img_fo_onePres' ...
  %'img_rc_mass_p1' ...
  'img_rc_mass_p2' ...
  %'img_fo_mass_p1' ...
  'img_fo_mass_p2' ...
  %'img_rc_spac2_p1' ...
  'img_rc_spac2_p2' ...
  %'img_fo_spac2_p1' ...
  'img_fo_spac2_p2' ...
  %'img_rc_spac12_p1' ...
  'img_rc_spac12_p2' ...
  %'img_fo_spac12_p1' ...
  'img_fo_spac12_p2' ...
  %'img_rc_spac32_p1' ...
  'img_rc_spac32_p2' ...
  %'img_fo_spac32_p1' ...
  'img_fo_spac32_p2' ...
  } ...
  { ...
  %'word_rc_onePres' ...
  % %
  %'word_fo_onePres' ...
  %'word_rc_mass_p1' ...
  'word_rc_mass_p2' ...
  %'word_fo_mass_p1' ...
  'word_fo_mass_p2' ...
  %'word_rc_spac2_p1' ...
  'word_rc_spac2_p2' ...
  %'word_fo_spac2_p1' ...
  'word_fo_spac2_p2' ...
  %'word_rc_spac12_p1' ...
  'word_rc_spac12_p2' ...
  %'word_fo_spac12_p1' ...
  'word_fo_spac12_p2' ...
  %'word_rc_spac32_p1' ...
  'word_rc_spac32_p2' ...
  %'word_fo_spac32_p1' ...
  'word_fo_spac32_p2' ...
  } ...
  } ...
  };

% exclude subjects with low event counts
[exper,ana] = mm_threshSubs_multiSes(exper,ana,10,[],'vert',evToCheck);

%% run it

for lat = 1:size(cfg_ana.latencies,1)
  cfg_ft.latency = cfg_ana.latencies(lat,:);
  for fr = 1:size(cfg_ana.frequencies,1)
    cfg_ft.frequency = cfg_ana.frequencies(fr,:);
    
    [stat_clus] = mm_ft_clusterstatTFR(cfg_ft,cfg_ana,exper,ana,dirs,data_pow);
  end
end

